name: CI Básico Alberto Rojas

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hola-mundo-Alberto-Rojas:
    runs-on: ubuntu-latest
    steps:
      - name: obtener el codigo del repositorio
        uses: actions/checkout@v4

      - name: instalar node.js
        uses: actions/setup-node@v4
        with:
          node-version: "26"

      - name: instalar dependencias
        run: npm install

      - name: ejecutar tests
        run: npm test
